create table "public"."Portfolio_Menus" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "location" text,
    "items" json,
    "created_at" timestamp with time zone default now()
);


alter table "public"."Portfolio_Menus" enable row level security;

create table "public"."Portfolio_Options" (
    "id" bigint generated by default as identity not null,
    "option" text,
    "value" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."Portfolio_Options" enable row level security;

create table "public"."Portfolio_Texts" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "content" text,
    "html" boolean default false,
    "created_at" timestamp with time zone default now()
);


alter table "public"."Portfolio_Texts" enable row level security;

create table "public"."Projects" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "stack" text,
    "repo" text,
    "link" text,
    "image" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."Projects" enable row level security;

CREATE UNIQUE INDEX "Portfolio_Menus_pkey" ON public."Portfolio_Menus" USING btree (id);

CREATE UNIQUE INDEX "Portfolio_Options_pkey" ON public."Portfolio_Options" USING btree (id);

CREATE UNIQUE INDEX "Portfolio_Texts_pkey" ON public."Portfolio_Texts" USING btree (id);

CREATE UNIQUE INDEX "Projects_pkey" ON public."Projects" USING btree (id);

alter table "public"."Portfolio_Menus" add constraint "Portfolio_Menus_pkey" PRIMARY KEY using index "Portfolio_Menus_pkey";

alter table "public"."Portfolio_Options" add constraint "Portfolio_Options_pkey" PRIMARY KEY using index "Portfolio_Options_pkey";

alter table "public"."Portfolio_Texts" add constraint "Portfolio_Texts_pkey" PRIMARY KEY using index "Portfolio_Texts_pkey";

alter table "public"."Projects" add constraint "Projects_pkey" PRIMARY KEY using index "Projects_pkey";


