alter table "public"."Portfolio_Menus" drop constraint "Portfolio_Menus_pkey";

alter table "public"."Portfolio_Options" drop constraint "Portfolio_Options_pkey";

alter table "public"."Portfolio_Texts" drop constraint "Portfolio_Texts_pkey";

alter table "public"."Projects" drop constraint "Projects_pkey";

drop index if exists "public"."Portfolio_Menus_pkey";

drop index if exists "public"."Portfolio_Options_pkey";

drop index if exists "public"."Portfolio_Texts_pkey";

drop index if exists "public"."Projects_pkey";

drop table "public"."Portfolio_Menus";

drop table "public"."Portfolio_Options";

drop table "public"."Portfolio_Texts";

drop table "public"."Projects";

create table "public"."portfolio_menus" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "location" text,
    "items" json,
    "created_at" timestamp with time zone default now()
);


alter table "public"."portfolio_menus" enable row level security;

create table "public"."portfolio_options" (
    "id" bigint generated by default as identity not null,
    "option" text,
    "value" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."portfolio_options" enable row level security;

create table "public"."portfolio_texts" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "content" text,
    "html" boolean default false,
    "created_at" timestamp with time zone default now()
);


alter table "public"."portfolio_texts" enable row level security;

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "stack" text,
    "repo" text,
    "link" text,
    "image" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX "Portfolio_Menus_pkey" ON public.portfolio_menus USING btree (id);

CREATE UNIQUE INDEX "Portfolio_Options_pkey" ON public.portfolio_options USING btree (id);

CREATE UNIQUE INDEX "Portfolio_Texts_pkey" ON public.portfolio_texts USING btree (id);

CREATE UNIQUE INDEX "Projects_pkey" ON public.projects USING btree (id);

alter table "public"."portfolio_menus" add constraint "Portfolio_Menus_pkey" PRIMARY KEY using index "Portfolio_Menus_pkey";

alter table "public"."portfolio_options" add constraint "Portfolio_Options_pkey" PRIMARY KEY using index "Portfolio_Options_pkey";

alter table "public"."portfolio_texts" add constraint "Portfolio_Texts_pkey" PRIMARY KEY using index "Portfolio_Texts_pkey";

alter table "public"."projects" add constraint "Projects_pkey" PRIMARY KEY using index "Projects_pkey";


